### ISSUE TITLE
Extention not compatible with 64bit version?

### ISSUE THREAD

**Issue by ColdEnd** [OfficerHalf/homebrewery-vscode#19]
Extention not compatible with 64bit version?
![homebrewery](https://user-images.githubusercontent.com/55524993/65214789-e6824480-da70-11e9-9c90-95a640840ed0.jpg)

I'm not sure if it is the 64bit version of code that is the problem OR if it is that I am running code 1.10.2.

By the way, thank you for putting this out there!

**Comment by nathonius** [comment]
I think the extension requires version 1.23 or above.

**Comment by ColdEnd** [comment]
You are correct, that solved it.
