### ISSUE TITLE
Needs support for installing to vscodium

### ISSUE THREAD

**Issue by buckleyc** [OfficerHalf/homebrewery-vscode#22]
Request: Add Homebrewery Markdown Preview extension to open-vsx.org for use with VSCodium.

Issue:
Using Visual Studio Code: homebrewery extension is found in extension marketplace.
Using VSCodium (vscodium.com): homebrewery extension is not found in default extension marketplace.

Currently:
I have both VSCode 1.55.0 and VSCodium 1.55.2 open. 
homebrewery-vscode is only available within the marketplace for VSCode.

Details:
The product.json file for VSCodium is set up to use open-vsx.org as extension gallery, versus VSCode's use of marketplace.visualstudio.com. (See https://github.com/VSCodium/vscodium/blob/master/DOCS.md#howto-vscode-marketplace)

Solution (recommended):
Can this extension be added to open-vsx.org?
Alternate Solution:
Users would need to modify the settings to use the Microsoft Marketplace, which may not be legal. See above link for details.

**Comment by nathonius** [comment]
I'm sorry, I have no intention to do this. Feel free to fork this repo and publish there. I'm not actively maintaining this anymore.
